url: http://www.newlode.com

title: 牛斗兄弟

keywords: 牛斗兄弟

description: 牛斗兄弟网络科技有限公司是华南地区内专业电商孵化机构，为品牌企业提供从市场调研分析、品牌定位策划、产品选型优化、店铺运营推广等全方位服务。

permalink: /products/:title.html

relative_permalinks: false

include:
  - .htaccess

exclude:
  - README.md
  - css
  - js

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - js
    - css
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  cache_assets: true
  gzip: []
